# Generated by Django 2.0.6 on 2018-07-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('url', models.URLField(help_text='Input url for parse')),
                ('title', models.CharField(help_text='title from url', max_length=200)),
                ('charset', models.CharField(help_text='encode from url', max_length=200)),
            ],
        ),
    ]
