# Generated by Django 2.0.6 on 2018-07-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pars', '0002_auto_20180705_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
