# Generated by Django 2.0.6 on 2018-07-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pars', '0007_auto_20180706_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmodel',
            name='time',
        ),
    ]
