# Generated by Django 2.0.6 on 2018-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pars', '0008_remove_urlmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
