# Generated by Django 2.0.6 on 2018-06-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_comment_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
