# Generated by Django 2.0.6 on 2018-06-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20180619_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'Blogger'), ('s', 'Simple User')], default='s', help_text='status of user', max_length=1),
        ),
    ]
